const COMPTE_COMPTABLE = {

    COTISATION_MEMBRE: 1,
    CREDIT_ACCORDE: 2,
    CAISSE: 3,
    CREDIT_REMBOURSE: 4,
    PENALITES: 5,
    INTERET_RECUS: 6,
    FRAIT_ADHESION: 7,
    CAISSE_SOCIALE: 8,
    COMMISSION: 9,
    COMPTE_NANCAIRE: 16,
    FRAIS_PERSONNEL: 18,
    INTERET_VERSE_SUR_EPARGNE: 19,
    DOTATION_AU_PROVISOIR: 20,
    FRAIS_FORMATION_MEMBRES: 21,
    AUDIT_CONFORMITE_BRB: 22,
    ACHAT_FOURNITURES: 23,
    ENTRETIEN_MAINTENANCE: 24,
    FRAIS_COMMUNICATION: 25,
    DEPLACEMENTS_MISSIONS: 26,
    LOYER_CHARGES_LOCATIVES: 27,
    DIVIDENDES_VERSES_MEMBRES: 28,
    DIVIDENDE_A_PAYER: 29,
    RESULTATS_EXERCICES: 30,
    RESERVES_GENERALE: 31,
    RESERVES_LEGALES: 32,
    CREDITS_A_RECOUVRER: 33,
    EXCEDENT_REPORTE: 34,
    CHARGES: 35 ,

}
module.exports = COMPTE_COMPTABLE

