const TYPE_OPERATION = {
    OCTROI_DU_CREDIT_EN_ESPECE: 2,
    PENALITES: 4,
    INTERET_PERCU: 5,
    COMMISSION_DE_REMBOURSEMENT_EN_ESPECE: 6,
    DEPOT_VERSEMENT: 7,
    RETRAIT_DE_FOND: 8,
    FRAIT_ADHESION_ESPECE: 10,
    COTISATION_MEMBRE_ESPECE: 11,
    CAISSE_SOCIALE: 13,
    COTISATION_MEMBRE_BANCAIRE: 17,
    FRAIT_ADHESION_BANCAIRE: 18,
    OCTROI_DU_CREDIT_BANCAIRE: 19,
    REMBOURSEMENT_BANCAIRE: 22,
    REMBOURSEMENT_ESPECE: 23,
    TRANSFERT_CAISSE_BANCAIRE: 24,
    TRANSFERT_BANCAIRE_CAISSE: 25,
    COMMISSION_DE_REMBOURSEMENT_BANCAIRE: 26
}
export default  TYPE_OPERATION

